redblue_join:
	python3 softjoin.py softjoin bluecorpus.txt redcorpus.txt --threshold 0.4

dedup_blue:
	python3 softjoin.py dedup bluecorpus.txt --threshold 0.8

dedup_red1:
	python3 softjoin.py dedup redcorpus.txt --threshold 0.8

dedup_red2:
	python3 softjoin.py dedup dedup-redcorpus.txt --threshold 0.8
